language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: pR3QCS2dvgxCTgc1NFnXDJxw5hyh87kCUICKty4qpqOw5bojwK852v8ALyVqfWS/PNnikW7mRUIvYvNLtHZpKq4NkUTrQUjeoL1uEFV+ERxId5aDkBjuv88d92M/khsf/utvGFOxTsWqsLViW92J4uHZ/Zfb9vbrvNNAMDlqnShuwJZwNBAUqAZLJiHnIC+1pDxh88eBXAmnbU6bs+xKN2GzLZjA/GgPBl1DPPE6S2AL1a2PPjwFhwFV7jGgTzfTaPPuUdpOP4KSde0v9LIYlDvtVGwZuUby79FDhQrUiVLZ/nLlSqguYeja2a4PJcb7Dw8+DjgJcA1LvFqqxy72GXEf85lJw//9vrvsow3Fk9ofrmYpdpW1tnAZsYZ3SBpTeKcWv36HRU8aV7zUUZaoOTGcO+2GOrxgHZrSK2Ek8kbDQ6SVnoS8+TsDLHDHSn+pKE0lH+ZxxuiWkdBs2lq9OqAKqpEliv2bRoKZ15i9+63UeGOAKLukbCjKLOAj8ZeJNjd7j0pyC6XENfycgqSPebNi1pkIl2eXixqVWgF7JpAfEBZTllrRURsejWVSuPR4B8wPhMyZU2MlgmK6mR4qiaHF3SsRSj5C9g6Fu69L7VOuhpCi6jjsbybOjesls5vfMBlYMKAE9YAgvLGMI5N4eKNPCf68gx1iOZhzcToTI6I=
  app: cool-app-name
  skip_cleanup: true
